eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-customer
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true      #¿ªÆô¶ÏÂ·Æ÷






