
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hello:
      path: /a/**
      serviceId: service-customer
    world:
      path: /b/**
      serviceId: service-user
### localhost:8765/a/hello  --- > service-item/hello
### localhost:8765/b/hello  --- > item-web/hello

